name: Build and test, clang and gcc

on:
  push:
    branches: [ main ]

jobs:
  clang_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install clang-10 make
    - run: make all
    - run: ./test.sh ./build/target
    - run: make clean
    - run: make BUILD=release CC=clang CXX=clang++ all
    - run: ./test.sh ./build/target

  gcc_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install gcc-10 make
    - run: make all
    - run: ./test.sh ./build/target
    - run: make clean
    - run: make BUILD=release CC=gcc CXX=g++ all
    - run: ./test.sh ./build/target
